name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run all tests
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          install-mise: 'true'
          mise-tools: just

      - name: Run all tests
        run: mise exec -- just test
